version: '2'
services:
    database:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        image: megento/mysql:5.7
        ports:
            - ${PORT_MYSQL}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_pmy
        image: megento/phpmyadmin:4.6
        ports:
            - ${PORT_PMY}:80
        links:
            - database:db
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        image: megento/magento2.3-php-fpm:7.2
        volumes:
            - ./application:/var/www/html
            - ./logs/php:/var/log
            - ./conf/composer/:/var/www/.composer
            - ./conf/composer/:/home/megento/.composer
            - ./conf/php/php.ini:/etc/php/7.2/fpm/conf.d/zzzz-custom.ini
            - ./conf/apache/envvars:/etc/apache2/envvars
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        image: megento/apache:2.4
        expose:
          - 80
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_EMAIL: 'jerome@megento.fr'
            FPM_HOST: php:9072
        volumes:
            - ./conf/apache/vhosts:/etc/apache2/sites-enabled/
            - ./conf/apache/envvars:/etc/apache2/envvars
            - ./application:/var/www/html
            - ./logs/apache:/var/log/apache2/
        links:
            - database:db
            - php

    session:
         image: redis:latest
         expose:
             - "6379"
         volumes:
             - /data/redis/cache:/data
         command: redis-server --appendonly yes --maxmemory 256M --maxmemory-policy volatile-lru

    cache:
        image: redis:latest
        expose:
            - "6379"
        volumes:
            - /data/redis/cache:/data
        command: redis-server --appendonly yes --maxmemory 256M --maxmemory-policy volatile-lru

    fpc:
        image: redis:latest
        expose:
            - "6379"
        volumes:
            - /data/redis/fpc:/data
        command: redis-server --appendonly yes --maxmemory 256M --maxmemory-policy volatile-lru

networks:
  default:
    external:
      name: nginx-proxy
