version: "2"

services:
  phpmyadmin:
    environment:
      - PMA_ARBITRARY=1
      #- PMA_HOST=
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
